### ISSUE TITLE
Why is paket needed for this repo?

### ISSUE THREAD

**Issue by cartermp** [fsharp/fsharp-core-docs#29]
All it's doing is pulling down FSharp.Core, and since this isn't a library there aren't even any special considerations for using FSharp.Core. I recommend removing it so we can remove an additional moving piece.

**Comment by baronfel** [comment]
It isn't needed anymore due to the changes to require a local fsharp.core, I concur with removing it for now.

**Comment by dsyme** [comment]
This line in FSharp.Core.fsproj is the line you would need to enable picking up a specified FSharp.Core version.  I guess we could adjust it to what's needed if a simple ProjectReference is used?

**Comment by cartermp** [comment]
The same FSharp.Core is already deployed by the .NET SDK, so if it's a question of the path to the binary, there's already one on any machine with the .NET SDK.

I think if we're to deploy different references based on the version of FSharp.Core, paket would be a good choice because each binary could be a group and we could build based on that.  But if that's not to be used then it's just using paket for the sake of using paket, which I don't want to get in the habit of displaying in OSS repos.

**Comment by dsyme** [comment]
Paket removed in #36

**Comment by dsyme** [comment]
> I think if we're to deploy different references based on the version of FSharp.Core, paket would be a good choice because each binary could be a group and we could build based on that.

Yup.
