### ISSUE TITLE
Links in TOC are bad

### ISSUE THREAD

**Issue by cartermp** [fsharp/fsharp-core-docs#41]
They're missing `/reference/` in their URL.

**Comment by baronfel** [comment]
Having issues reproducing this to work on a fix, the build of F#F I'm getting right now doesn't seem to be replacing the `{{list-of-namespaces}}` template parameter in the html template.

**Comment by baronfel** [comment]
Looking at the F#F code though, the doc comments on the `UrlBaseName` members (which are used to generate the namespace list html) explicitly mention not having the `/reference/` segment on there, so it might be as simple as prefixing that wherever those members are used.

**Comment by baronfel** [comment]
Though seeing how prevalent the use of those members are, I question the value of _not_ prepending the `/reference/` to the UrlBaseName, so they they are correct by construction.

**Comment by dsyme** [comment]
> Though seeing how prevalent the use of those members are, I question the value of not prepending the /reference/ to the UrlBaseName, so they they are correct by construction.

This is likely right.  BTW I've been trying to clarify the various namings or URL things in F#F - a persistent source of bugs - might be better to make a type distinction

**Comment by dsyme** [comment]
I'm working on fixing this

**Comment by dsyme** [comment]
A bit of a snafu on the docs right now, sorting it out now.  F# Formatting is setting `root` incorrectly.

Hilariously it means the old F# logo turned up on the site :-)

https://fsharp.github.io/img/logo.png

**Comment by dsyme** [comment]
Fixed by https://github.com/fsprojects/FSharp.Formatting/pull/570
