### ISSUE TITLE
CSS/JS/Icons aren't being served at the expected locations

### ISSUE THREAD

**Issue by baronfel** [fsharp/fsharp-core-docs#46]
Currently deployed state is making the following requests:

![image](https://user-images.githubusercontent.com/573979/89304888-9c2b9700-d633-11ea-9f0c-7a059f7abaf2.png)

Most of the JS/CSS/icons are 404'ing, and they're being requested from `/content/<filename>`.  Need to check that the requested paths are consistent with what F#F is outputting.

**Comment by baronfel** [comment]
Oh, this is the same issue as the entity URL problems: the `{{root}}` isn't being prepended to the generated links.

**Comment by dsyme** [comment]
I've got this fixed

**Comment by dsyme** [comment]
Fixed by https://github.com/fsprojects/FSharp.Formatting/pull/570
