### ISSUE TITLE
SI Unit names namespace not visible

### ISSUE THREAD

**Issue by cartermp** [fsharp/fsharp-core-docs#57]
See here: https://fsharp.github.io/fsharp-core-docs/reference/fsharp-data-unitsystems-si-unitnames.html

It does appear as a search entry.

**Comment by dsyme** [comment]
Yeah the two darn namespaces are so long and over-dramatic considering no one uses this stuff, I did suppress it pending what to do about it.  The sheer length of the names cause spacing problems in any navigation bar

We can add it back in somehow, either by removing the suppression - let's discuss, I can send you the screenshots

**Comment by cartermp** [comment]
I think it's better not to suppress for now and once we have everything up and working okay we can figure out how to handle it.

**Comment by dsyme** [comment]
Well, TBH I had to to avoid overflow problems in the navigation panel.  Plus I hate the look of them dominating the list.  

Another approach might be just to show first level namespaces, which would show "FSharp.Data", and usefully de-emphasize "FSharp.Core.CompilerServices" and "FSharp.Linq.RuntimeHelpers" which aren't exactly high on anyone's learning list.

**Comment by dsyme** [comment]
Oh I see, it's not just that it's not in the namespace list, it's actually not even showing at https://fsharp.github.io/fsharp-core-docs/reference/fsharp-data-unitsystems-si-unitnames.html

**Comment by dsyme** [comment]
Individual units are showing, e.g. https://fsharp.github.io/fsharp-core-docs/reference/fsharp-data-unitsystems-si-unitsymbols-ohm.html

BTW on that page the display of the abbreviated unit of measure is a bit warped, it's showing the canonical form, there is code that's meant to do the right thing here: https://github.com/fsprojects/FSharp.Formatting/blob/a87e2e3d44d720f7732424871b2d8a976d9e1c4a/src/FSharp.Formatting.ApiDocs/GenerateModel.fs#L801

**Comment by dsyme** [comment]
These are showing on the namespace page now, though not in the index, which we can discuss in #59
