### ISSUE TITLE
CI build is having trouble

### ISSUE THREAD

**Issue by dsyme** [fsharp/fsharp-core-docs#64]
CI build is having trouble building the dotnet/fsharp repo on a CI server, 

THis is because we hit this error

> C:\Users\runneradmin\.nuget\packages\xlifftasks\1.0.0-beta.20206.1\build\XliffTasks.targets(91,5): error : '..\xlf\FSComp.txt.es.xlf' is out-of-date with 'D:\a\fsharp-core-docs\fsharp-core-docs\fsharp\artifacts\obj\FSharp.Compiler.Private\Debug\netstandard2.0\FSComp.resx'. Run `msbuild /t:UpdateXlf` to update .xlf files or set UpdateXlfOnBuild=true to update them on every build, but note that it is strongly discouraged to set UpdateXlfOnBuild=true in official/CI build environments as they should not modify source code during the build. [D:\a\fsharp-core-docs\fsharp-core-docs\fsharp\src\fsharp\FSharp.Compiler.Private\FSharp.Compiler.Private.fsproj]

I'm fiddling with the recommended changes to get it to go through here: https://github.com/fsharp/fsharp-core-docs/blob/master/.github/workflows/docs.yml#L31  but I can't quite seem to get it right

**Comment by dsyme** [comment]
The relevant thing in the F# repo is here: https://github.com/dotnet/fsharp/blob/d53716c48c1a9b78cb249cadb6065758122bd686/FSharpBuild.Directory.Build.props#L71

**Comment by dsyme** [comment]
Ugh I don't actually know how to solve this.  I'm makingone more attempt to set the recommended environment variables here: https://github.com/fsharp/fsharp-core-docs/blob/master/.github/workflows/docs.yml#L32

The problem is the fsharp build uses some different more restrictive settings when run on the CI server. Or something like that

**Comment by cartermp** [comment]
Maybe try running this? https://github.com/dotnet/fsharp/blob/master/eng/CIBuild.cmd

**Comment by dsyme** [comment]
Thanks! trying the `-ci` flag now

**Comment by dsyme** [comment]
Seems fixed now
