### ISSUE TITLE
Incorrect Option.flatten return description

### ISSUE THREAD

**Issue by Jordan466** [fsharp/fsharp-core-docs#70]
The return description here seems to be for Option.bind, and not using it's own description.

https://fsharp.github.io/fsharp-core-docs/reference/fsharp-core-optionmodule.html#flatten
![image](https://user-images.githubusercontent.com/24884680/109180520-eb9b0580-77c5-11eb-991a-ed14f8ea6e8d.png)

**Comment by dsyme** [comment]
@Jordan466 Any chance you could you submit PRs fixing this as you find them to https://github.com/dotnet/fsharp ?  We can then activate here
