### ISSUE TITLE
FSharp.NativeInterop links to incorrect document on home page

### ISSUE THREAD

**Issue by awedd95** [fsharp/fsharp-core-docs#73]
FSharp.NativeInterop link on https://fsharp.github.io/fsharp-core-docs/ links through to https://fsharp.github.io/fsharp-core-docs/reference/fsharp-linq.html instead of https://fsharp.github.io/fsharp-core-docs/reference/fsharp-nativeinterop.html

**Comment by baronfel** [comment]
I just updated this link in the index.md, and after the pipeline finished it should push out to the live site.

**Comment by awedd95** [comment]
Awesome thanks!
