### ISSUE TITLE
404 Error for all module reference pages

### ISSUE THREAD

**Issue by jamesh1999** [fsharp/fsharp-core-docs#93]
Since the latest commit, it appears all the module reference pages are unavailable. (Might not coincide exactly, I last was able to view them earlier this week.)

https://fsharp.github.io/fsharp-core-docs/reference/fsharp-core.html

**Comment by TheAngryByrd** [comment]
fsdocs failed to run correctly here:

<img width="620" alt="image" src="https://github.com/fsharp/fsharp-core-docs/assets/1490044/7eac5254-73e9-4201-b61e-628cce53d9dd">

---

Current fix is most like the same listed in https://github.com/ionide/ionide-vscode-fsharp/issues/1888#issuecomment-1615197461. Set the [environment variable ](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables#dotnet_roll_forward) `DOTNET_ROLL_FORWARD=LatestMajor`.

I don't have time now to make a PR but someone else can try to fix the github action.

**Comment by baronfel** [comment]
I've got a PR up for this at #94

**Comment by jamesh1999** [comment]
Thanks for sorting. I'll mark this as closed
